CREATE TABLE "USR_USER"
(
  ID bigserial NOT NULL,
  USER_NAME VARCHAR(30) NOT NULL,
  EMAIL VARCHAR(50) NOT NULL,
  PASSWORD text NOT NULL,
  CONSTRAINT user_pkey PRIMARY KEY (id)
);

CREATE SEQUENCE usr_user_id_seq START 1;